#!/bin/bash
. ./nodes.conf

i=0
len=${#allnodes[@]}
echo $len
while [ $i -lt $len ]
do
    myip=${allnodes[$i]}
    echo "********  set ssh at $myip  ********"
    cat /root/.ssh/id_rsa.pub | ssh root@$myip 'mkdir -p ~/.ssh;sh -c "cat - > ~/.ssh/authorized_keys;chmod -R 700 ~/.ssh"'
    let i++
done

i=0
len=${#allnodes[@]}
echo $len
while [ $i -lt $len ]
do
    cat ./nodes.conf > ./install_script
    myip=${allnodes[$i]}
    echo $myip
    echo "myip=$myip" >> ./install_script
    echo "myname=${allnames[$i]}" >> ./install_script
    cat ./install_node >> ./install_script
    chmod +x ./install_script
    ssh -n root@$myip 'sh -c "rm -rf /opt/cscloud;mkdir -p /opt/cscloud"'
    scp ./install_script ./env_hadoop.conf ./env_java.conf ./config_selinux ./hdfs-site-tmp.xml ./mapred-site-tmp.xml ./core-site-tmp.xml ./hadoop-1.2.1.tar.gz jdk-7u25-linux-x64.tar.gz root@$myip:/opt/cscloud/
    echo "********  Run install script on $myip  ********"
    ssh root@$myip 'sh -c "/opt/cscloud/install_script"'
    scp root@$myip:/root/.ssh/id_rsa.pub ./${allnames[$i]}.pub
    let i++
done

rm ./install_script

i=0
len=${#allnodes[@]}
while [ $i -lt $len ]
do
    sshfile=${allnames[$i]}.pub
    j=0
    while [ $j -lt $len ]
    do
        myip=${allnodes[$j]}
        echo "********  add public key of ${allnodes[$i]} to $myip  ********"
        cat $sshfile | ssh root@$myip 'sh -c "cat - >>~/.ssh/authorized_keys;"'
        let j++
    done
    let i++
    rm $sshfile
done

